dontChroot: true
timeout: 10
verbose: true

script:
  - "rm -f ${ROOT}/etc/resolv.conf"
  - "cp -L /run/systemd/resolve/resolv.conf ${ROOT}/etc/resolv.conf"

i18n:
  name: "Preparing network connection"
