dontChroot: false
timeout: 30
verbose: true

script:
  - "systemctl disable pacman-init.service || true"
  - "rm -f /etc/systemd/system/multi-user.target.wants/pacman-init.service"
  - "rm -f /etc/systemd/system/pacman-init.service"
  - "rm -f /etc/systemd/system/etc-pacman.d-gnupg.mount"

  - "rm -f /etc/sddm.conf.d/autologin.conf"

  - "rm -f /etc/skel/.config/plasma-welcomerc"
  - "rm -f /home/${USER}/.config/plasma-welcomerc"

  - "rm -f /etc/skel/.config/systemd/user/plasma-login-kwin_wayland.service.d/override.conf"
  - "rm -f /home/${USER}/.config/systemd/user/plasma-login-kwin_wayland.service.d/override.conf"

  - "rm -rf /home/liveuser"

  i18n:
    name: "Removing live environment configurations"
