dontChroot: true
timeout: 30
verbose: true

script:
  - "chattr +C ${ROOT}/boot"
  - "rm -f ${ROOT}/boot/vmlinuz-linux"
  - "install -m 0644 /dev/null ${ROOT}/boot/vmlinuz-linux"
  - "chattr +C ${ROOT}/boot/vmlinuz-linux"
  - "cp --reflink=never /run/archiso/bootmnt/pytuna/boot/x86_64/vmlinuz-linux ${ROOT}/boot/vmlinuz-linux"
  - "sync"
    
i18n:
  name: "Installing Linux kernel"
