dontChroot: false
timeout: 120

script:
  - "rm -f /etc/mkinitcpio.d/linux.preset"
  - "rm -f /etc/mkinitcpio.conf.d/archiso.conf"
  - "install -d /etc/mkinitcpio.d"
  - "sed 's/%PKGBASE%/linux/g' /usr/share/mkinitcpio/hook.preset > /etc/mkinitcpio.d/linux.preset"
  
i18n:
  name: "Removing live boot configuration"
