dontChroot: false
timeout: 300
verbose: true

script:
  - "install -d -m 0755 /etc/pacman.d/gnupg"
  - command: "pacman-key --init"
    timeout: 300
    verbose: true
  - command: "pacman-key --populate archlinux pytuna chaotic"
    timeout: 300
    verbose: true

i18n:
  name: "Initializing package keys"
